name: pr
on:
  pull_request:
    branches:
      - main

jobs:
  dependencies:
    uses: the-guild-org/shared-config/.github/workflows/changesets-dependencies.yaml@main
    with:
      installDependencies: true
      packageManager: yarn
      nodeVersion: 18
      preCommit: 'yarn prettier'
    secrets:
      githubToken: ${{ secrets.GUILD_BOT_TOKEN }}

  release:
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@main
    with:
      npmTag: alpha
      buildScript: build
      nodeVersion: 18
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}

  algolia:
    uses: the-guild-org/shared-config/.github/workflows/algolia-integrity.yml@main
    with:
      domain: https://www.the-guild.dev/graphql/envelop/
      source: 'Envelop'
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
