name: pr
on:
  pull_request:
    branches:
      - main

jobs:
  dependencies:
    uses: the-guild-org/shared-config/.github/workflows/changesets-dependencies.yaml@main
    if: ${{ github.event.pull_request.title != 'Upcoming Release Changes' }}
    with:
      installDependencies: true
      packageManager: pnpm
      nodeVersion: 18
      preCommit: 'pnpm run prettier'
    secrets:
      githubToken: ${{ secrets.GUILD_BOT_TOKEN }}

  alpha:
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@main
    if: ${{ github.event.pull_request.title != 'Upcoming Release Changes' }}
    with:
      npmTag: alpha
      buildScript: build
      nodeVersion: 18
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}

  release-candidate:
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@main
    if: ${{ github.event.pull_request.title == 'Upcoming Release Changes' }}
    with:
      npmTag: rc
      restoreDeletedChangesets: true
      buildScript: build
      nodeVersion: 18
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}

  algolia:
    uses: the-guild-org/shared-config/.github/workflows/algolia-integrity.yml@main
    with:
      domain: https://www.the-guild.dev/graphql/envelop/
      source: 'Envelop'
      packageManager: 'pnpm'
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
