name: release
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  stable:
    uses: the-guild-org/shared-config/.github/workflows/release-stable.yml@v1-corepack
    with:
      releaseScript: release
    secrets:
      githubToken: ${{ secrets.GUILD_BOT_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}
