name: release
on:
  push:
    branches:
      - main

jobs:
  stable:
    uses: the-guild-org/shared-config/.github/workflows/release-stable.yml@main
    with:
      releaseScript: release
      nodeVersion: 20
      packageManager: 'pnpm'
    secrets:
      githubToken: ${{ secrets.GUILD_BOT_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}

  algolia:
    uses: the-guild-org/shared-config/.github/workflows/algolia-publish.yml@main
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      algoliaAdminApiKey: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
    with:
      domain: https://www.the-guild.dev/graphql/envelop/
      source: 'Envelop'
      packageManager: 'pnpm'
