name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: 17
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-17-16-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-17-16-yarn-
      - name: Install Dependencies
        run: yarn install --ignore-engines && git checkout yarn.lock

      - name: Lint ESLint
        run: yarn lint

      - name: Lint Prettier
        run: yarn lint:prettier
  build:
    name: Type Check on GraphQL v${{matrix.graphql_version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        graphql_version: [15, 16]
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: 17
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-16-${{matrix.graphql_version}}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-16-yarn-
      - name: Use GraphQL v${{matrix.graphql_version}}
        run: node ./scripts/match-graphql.js ${{matrix.graphql_version}}
      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Build
        run: yarn ts:check
  test:
    name: Unit Test on Node ${{matrix.node-version}} (${{matrix.os}}) and GraphQL v${{matrix.graphql_version}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest] # remove windows to speed up the tests
        node-version: [12, 17]
        graphql_version: [15, 16]
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-${{matrix.node-version}}-${{matrix.graphql_version}}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{matrix.node-version}}-${{matrix.graphql_version}}-yarn-
      - name: Use GraphQL v${{matrix.graphql_version}}
        run: node ./scripts/match-graphql.js ${{matrix.graphql_version}}
      - name: Install Dependencies
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Cache Jest
        uses: actions/cache@v2
        with:
          path: .cache/jest
          key: ${{ runner.os }}-${{matrix.node-version}}-${{matrix.graphql_version}}-jest-${{ hashFiles('yarn.lock') }}-${{ hashFiles('patches/*.patch') }}
      - name: Test
        run: yarn test --ci
        env:
          CI: true
  test_esm:
    name: ESM Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: 17
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-17-16-yarn-${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Build Packages
        run: yarn build
      - name: Test ESM & CJS exports integrity
        run: yarn bob check
