name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: check / graphql v${{matrix.graphql_version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        graphql_version: [15.8.0, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup env
        uses: the-guild-org/shared-config/setup@v1
      - name: Use GraphQL v${{matrix.graphql_version}}
        run: node ./scripts/match-graphql.js ${{matrix.graphql_version}}
      - name: Install Dependencies using pnpm
        run: pnpm install --no-frozen-lockfile && git checkout pnpm-lock.yaml
      - name: Lint Prettier
        run: pnpm run lint:prettier
      - name: Lint
        run: pnpm run ci:lint && pnpm run lint
      - name: Build
        run: pnpm run ts:check
      - name: Test ESM & CJS exports integrity
        run: pnpm bob check

  unit:
    name:
      Unit Test / ${{matrix.os}} / node v${{matrix.node-version}} / graphql
      v${{matrix.graphql_version}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest] # remove windows to speed up the tests
        node-version: [18, 20, 22]
        graphql_version: [15, 16]
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
      - name: Setup env
        uses: the-guild-org/shared-config/setup@v1
      - name: Use GraphQL v${{matrix.graphql_version}}
        run: node ./scripts/match-graphql.js ${{matrix.graphql_version}}
      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile && git checkout pnpm-lock.yaml
      - name: Cache Jest
        uses: actions/cache@v4
        with:
          path: .cache/jest
          key:
            ${{ runner.os }}-${{matrix.node-version}}-${{matrix.graphql_version}}-jest-${{
            hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('patches/*.patch') }}
      - name: Test
        run: pnpm run test --ci
        env:
          CI: true

  test_esm:
    name: esm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup env
        uses: the-guild-org/shared-config/setup@v1
      - name: Build Packages
        run: pnpm run build
